### ISSUE TITLE
Provide separate `COPYING` file

### ISSUE THREAD

**Issue by vinipsmaker** [adeverteuil/console-solarized#2]
It'd help a lot on build scripts like [this one](https://aur.archlinux.org/packages/co/console-solarized-git/PKGBUILD).

I'd no longer need to extract the `COPYING` file through obscure commands like:

```
sed -n '/^Copying$/ { s///; :a; n; p; ba; }' README.rst | tail -n +3 "${pkgdir}/usr/share/licenses/${_pkgname}/COPYING"
```

**Comment by adeverteuil** [comment]
Done! Sorry for the long delay...

**Comment by vinipsmaker** [comment]
Thanks. I've updated the PKGBUILD.
